"""Crear tabla contratos_procesados

Revision ID: 2b66f40b4627
Revises: 293b580b893f
Create Date: 2026-05-12 00:25:52.284163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b66f40b4627'
down_revision: Union[str, Sequence[str], None] = '293b580b893f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contratos_procesados',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('raw_data_id', sa.BigInteger(), nullable=True),
    sa.Column('id_proceso', sa.String(length=100), nullable=True),
    sa.Column('entidad', sa.Text(), nullable=True),
    sa.Column('proveedor', sa.Text(), nullable=True),
    sa.Column('valor_contrato', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('fecha_contrato', sa.Date(), nullable=True),
    sa.Column('tipo_contrato', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.String(length=100), nullable=True),
    sa.Column('normalized_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contratos_procesados_entidad'), 'contratos_procesados', ['entidad'], unique=False)
    op.create_index(op.f('ix_contratos_procesados_fecha_contrato'), 'contratos_procesados', ['fecha_contrato'], unique=False)
    op.create_index(op.f('ix_contratos_procesados_id_proceso'), 'contratos_procesados', ['id_proceso'], unique=False)
    op.create_index(op.f('ix_contratos_procesados_normalized_hash'), 'contratos_procesados', ['normalized_hash'], unique=True)
    op.create_index(op.f('ix_contratos_procesados_proveedor'), 'contratos_procesados', ['proveedor'], unique=False)
    op.create_index(op.f('ix_contratos_procesados_raw_data_id'), 'contratos_procesados', ['raw_data_id'], unique=False)
    op.create_index(op.f('ix_contratos_procesados_tipo_contrato'), 'contratos_procesados', ['tipo_contrato'], unique=False)
    op.create_index(op.f('ix_contratos_procesados_valor_contrato'), 'contratos_procesados', ['valor_contrato'], unique=False)
    op.create_table('sincronizacion_historial',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fuente_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registros_traidos', sa.BigInteger(), nullable=True),
    sa.Column('registros_insertados', sa.BigInteger(), nullable=True),
    sa.Column('registros_duplicados', sa.BigInteger(), nullable=True),
    sa.Column('estado', sa.Enum('EN_PROCESO', 'EXITOSO', 'ERROR', name='estadosync'), nullable=True),
    sa.Column('mensaje_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['fuente_id'], ['fuentes_datos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sincronizacion_historial')
    op.drop_index(op.f('ix_contratos_procesados_valor_contrato'), table_name='contratos_procesados')
    op.drop_index(op.f('ix_contratos_procesados_tipo_contrato'), table_name='contratos_procesados')
    op.drop_index(op.f('ix_contratos_procesados_raw_data_id'), table_name='contratos_procesados')
    op.drop_index(op.f('ix_contratos_procesados_proveedor'), table_name='contratos_procesados')
    op.drop_index(op.f('ix_contratos_procesados_normalized_hash'), table_name='contratos_procesados')
    op.drop_index(op.f('ix_contratos_procesados_id_proceso'), table_name='contratos_procesados')
    op.drop_index(op.f('ix_contratos_procesados_fecha_contrato'), table_name='contratos_procesados')
    op.drop_index(op.f('ix_contratos_procesados_entidad'), table_name='contratos_procesados')
    op.drop_table('contratos_procesados')
    # ### end Alembic commands ###
