"""Add proveedor adjudicacion directa

Revision ID: 32f03dcec0ef
Revises: 8a4ca16f08e8
Create Date: 2026-05-13 19:42:34.061449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32f03dcec0ef'
down_revision: Union[str, Sequence[str], None] = '8a4ca16f08e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contrato_outlier',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contrato_id', sa.BigInteger(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('grupo', sa.String(length=255), nullable=False),
    sa.Column('campo_analizado', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('q1', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('q3', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('iqr', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('limite_inferior', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('limite_superior', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('es_outlier', sa.Boolean(), nullable=False),
    sa.Column('direccion_outlier', sa.String(length=10), nullable=True),
    sa.Column('score', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('fecha_calculo', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contrato_outlier_contrato_id', 'contrato_outlier', ['contrato_id'], unique=False)
    op.create_index('ix_contrato_outlier_es_outlier', 'contrato_outlier', ['es_outlier'], unique=False)
    op.create_index('ix_contrato_outlier_grupo', 'contrato_outlier', ['grupo'], unique=False)
    op.create_index('ix_contrato_outlier_run_id', 'contrato_outlier', ['run_id'], unique=False)
    op.create_table('proveedor_adjudicacion_directa',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('contrato_id', sa.BigInteger(), nullable=True),
    sa.Column('proveedor', sa.String(length=500), nullable=False),
    sa.Column('nit_proveedor', sa.String(length=100), nullable=True),
    sa.Column('entidad', sa.String(length=500), nullable=True),
    sa.Column('tipo_contrato', sa.String(length=255), nullable=True),
    sa.Column('modalidad_contratacion', sa.String(length=255), nullable=True),
    sa.Column('fecha_contrato', sa.Date(), nullable=True),
    sa.Column('total_contratos', sa.Integer(), nullable=False),
    sa.Column('contratos_directos', sa.Integer(), nullable=False),
    sa.Column('porcentaje_directos', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('score_riesgo', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('clasificacion_riesgo', sa.String(length=50), nullable=False),
    sa.Column('fecha_calculo', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prov_adjdir_clasificacion_riesgo', 'proveedor_adjudicacion_directa', ['clasificacion_riesgo'], unique=False)
    op.create_index('ix_prov_adjdir_porcentaje_directos', 'proveedor_adjudicacion_directa', ['porcentaje_directos'], unique=False)
    op.create_index('ix_prov_adjdir_proveedor', 'proveedor_adjudicacion_directa', ['proveedor'], unique=False)
    op.create_index('ix_prov_adjdir_run_id', 'proveedor_adjudicacion_directa', ['run_id'], unique=False)
    op.create_index('ix_prov_adjdir_score_riesgo', 'proveedor_adjudicacion_directa', ['score_riesgo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prov_adjdir_score_riesgo', table_name='proveedor_adjudicacion_directa')
    op.drop_index('ix_prov_adjdir_run_id', table_name='proveedor_adjudicacion_directa')
    op.drop_index('ix_prov_adjdir_proveedor', table_name='proveedor_adjudicacion_directa')
    op.drop_index('ix_prov_adjdir_porcentaje_directos', table_name='proveedor_adjudicacion_directa')
    op.drop_index('ix_prov_adjdir_clasificacion_riesgo', table_name='proveedor_adjudicacion_directa')
    op.drop_table('proveedor_adjudicacion_directa')
    op.drop_index('ix_contrato_outlier_run_id', table_name='contrato_outlier')
    op.drop_index('ix_contrato_outlier_grupo', table_name='contrato_outlier')
    op.drop_index('ix_contrato_outlier_es_outlier', table_name='contrato_outlier')
    op.drop_index('ix_contrato_outlier_contrato_id', table_name='contrato_outlier')
    op.drop_table('contrato_outlier')
    # ### end Alembic commands ###
