"""crear tabla fuentes_datos

Revision ID: 4abb96316f8b
Revises: 
Create Date: 2026-05-10 20:03:05.348751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4abb96316f8b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fuentes_datos', 'api_key',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Almacenado encriptado con Fernet',
               existing_nullable=True)
    op.alter_column('fuentes_datos', 'frecuencia_dias',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Intervalo de sincronización automática en días',
               existing_nullable=False,
               existing_server_default=sa.text('15'))
    op.create_index(op.f('ix_fuentes_datos_id'), 'fuentes_datos', ['id'], unique=False)
    op.drop_table_comment(
        'fuentes_datos',
        existing_comment='Registro de proveedores de datos externos',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'fuentes_datos',
        'Registro de proveedores de datos externos',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_fuentes_datos_id'), table_name='fuentes_datos')
    op.alter_column('fuentes_datos', 'frecuencia_dias',
               existing_type=sa.INTEGER(),
               comment='Intervalo de sincronización automática en días',
               existing_nullable=False,
               existing_server_default=sa.text('15'))
    op.alter_column('fuentes_datos', 'api_key',
               existing_type=sa.TEXT(),
               comment='Almacenado encriptado con Fernet',
               existing_nullable=True)
    # ### end Alembic commands ###
