"""Refactor contratos_procesados y crear anomalias y estadisticas

Revision ID: 6486afd78c3a
Revises: 2b66f40b4627
Create Date: 2026-05-12 01:32:00.979951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6486afd78c3a'
down_revision: Union[str, Sequence[str], None] = '2b66f40b4627'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estadistica_campos_faltantes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nombre_campo', sa.String(length=100), nullable=False),
    sa.Column('contador_faltantes', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estadistica_campos_faltantes_nombre_campo'), 'estadistica_campos_faltantes', ['nombre_campo'], unique=True)
    op.create_table('contrato_anomalo_incompleto',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('raw_secop_id', sa.BigInteger(), nullable=False),
    sa.Column('motivo', sa.String(length=50), nullable=False),
    sa.Column('campo_afectado', sa.String(length=100), nullable=False),
    sa.Column('valor_detectado', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_secop_id'], ['raw_secop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cai_campo', 'contrato_anomalo_incompleto', ['campo_afectado'], unique=False)
    op.create_index('ix_cai_motivo', 'contrato_anomalo_incompleto', ['motivo'], unique=False)
    op.create_index(op.f('ix_contrato_anomalo_incompleto_raw_secop_id'), 'contrato_anomalo_incompleto', ['raw_secop_id'], unique=False)
    op.add_column('contratos_procesados', sa.Column('raw_secop_id', sa.BigInteger(), nullable=False))
    op.add_column('contratos_procesados', sa.Column('id_del_proceso', sa.String(length=100), nullable=True))
    op.add_column('contratos_procesados', sa.Column('entidad_normalizada', sa.Text(), nullable=True))
    op.add_column('contratos_procesados', sa.Column('nit_entidad', sa.String(length=50), nullable=True))
    op.add_column('contratos_procesados', sa.Column('proveedor_normalizado', sa.Text(), nullable=True))
    op.add_column('contratos_procesados', sa.Column('nit_proveedor', sa.String(length=50), nullable=True))
    op.add_column('contratos_procesados', sa.Column('fecha_publicacion_normalizada', sa.Date(), nullable=True))
    op.add_column('contratos_procesados', sa.Column('fecha_adjudicacion_normalizada', sa.Date(), nullable=True))
    op.add_column('contratos_procesados', sa.Column('valor_total_normalizado', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('contratos_procesados', sa.Column('precio_base_normalizado', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('contratos_procesados', sa.Column('tipo_contrato_normalizado', sa.String(length=200), nullable=True))
    op.add_column('contratos_procesados', sa.Column('modalidad_contratacion', sa.String(length=200), nullable=True))
    op.add_column('contratos_procesados', sa.Column('estado_normalizado', sa.String(length=100), nullable=True))
    op.add_column('contratos_procesados', sa.Column('ciudad_entidad', sa.String(length=100), nullable=True))
    op.add_column('contratos_procesados', sa.Column('departamento_entidad', sa.String(length=100), nullable=True))
    op.add_column('contratos_procesados', sa.Column('urlproceso', sa.Text(), nullable=True))
    op.alter_column('contratos_procesados', 'normalized_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('contratos_procesados', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_contratos_procesados_entidad'), table_name='contratos_procesados')
    op.drop_index(op.f('ix_contratos_procesados_fecha_contrato'), table_name='contratos_procesados')
    op.drop_index(op.f('ix_contratos_procesados_id_proceso'), table_name='contratos_procesados')
    op.drop_index(op.f('ix_contratos_procesados_proveedor'), table_name='contratos_procesados')
    op.drop_index(op.f('ix_contratos_procesados_raw_data_id'), table_name='contratos_procesados')
    op.drop_index(op.f('ix_contratos_procesados_tipo_contrato'), table_name='contratos_procesados')
    op.drop_index(op.f('ix_contratos_procesados_valor_contrato'), table_name='contratos_procesados')
    op.create_index(op.f('ix_contratos_procesados_entidad_normalizada'), 'contratos_procesados', ['entidad_normalizada'], unique=False)
    op.create_index(op.f('ix_contratos_procesados_fecha_adjudicacion_normalizada'), 'contratos_procesados', ['fecha_adjudicacion_normalizada'], unique=False)
    op.create_index(op.f('ix_contratos_procesados_fecha_publicacion_normalizada'), 'contratos_procesados', ['fecha_publicacion_normalizada'], unique=False)
    op.create_index(op.f('ix_contratos_procesados_id_del_proceso'), 'contratos_procesados', ['id_del_proceso'], unique=False)
    op.create_index(op.f('ix_contratos_procesados_proveedor_normalizado'), 'contratos_procesados', ['proveedor_normalizado'], unique=False)
    op.create_index(op.f('ix_contratos_procesados_raw_secop_id'), 'contratos_procesados', ['raw_secop_id'], unique=False)
    op.create_index(op.f('ix_contratos_procesados_tipo_contrato_normalizado'), 'contratos_procesados', ['tipo_contrato_normalizado'], unique=False)
    op.create_index(op.f('ix_contratos_procesados_valor_total_normalizado'), 'contratos_procesados', ['valor_total_normalizado'], unique=False)
    op.create_index('ix_cp_entidad_fecha', 'contratos_procesados', ['entidad_normalizada', 'fecha_publicacion_normalizada'], unique=False)
    op.create_index('ix_cp_tipo_valor', 'contratos_procesados', ['tipo_contrato_normalizado', 'valor_total_normalizado'], unique=False)
    op.create_foreign_key(None, 'contratos_procesados', 'raw_secop', ['raw_secop_id'], ['id'])
    op.drop_column('contratos_procesados', 'raw_data_id')
    op.drop_column('contratos_procesados', 'proveedor')
    op.drop_column('contratos_procesados', 'entidad')
    op.drop_column('contratos_procesados', 'tipo_contrato')
    op.drop_column('contratos_procesados', 'valor_contrato')
    op.drop_column('contratos_procesados', 'id_proceso')
    op.drop_column('contratos_procesados', 'estado')
    op.drop_column('contratos_procesados', 'updated_at')
    op.drop_column('contratos_procesados', 'fecha_contrato')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contratos_procesados', sa.Column('fecha_contrato', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('contratos_procesados', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('contratos_procesados', sa.Column('estado', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('contratos_procesados', sa.Column('id_proceso', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('contratos_procesados', sa.Column('valor_contrato', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True))
    op.add_column('contratos_procesados', sa.Column('tipo_contrato', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('contratos_procesados', sa.Column('entidad', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('contratos_procesados', sa.Column('proveedor', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('contratos_procesados', sa.Column('raw_data_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'contratos_procesados', type_='foreignkey')
    op.drop_index('ix_cp_tipo_valor', table_name='contratos_procesados')
    op.drop_index('ix_cp_entidad_fecha', table_name='contratos_procesados')
    op.drop_index(op.f('ix_contratos_procesados_valor_total_normalizado'), table_name='contratos_procesados')
    op.drop_index(op.f('ix_contratos_procesados_tipo_contrato_normalizado'), table_name='contratos_procesados')
    op.drop_index(op.f('ix_contratos_procesados_raw_secop_id'), table_name='contratos_procesados')
    op.drop_index(op.f('ix_contratos_procesados_proveedor_normalizado'), table_name='contratos_procesados')
    op.drop_index(op.f('ix_contratos_procesados_id_del_proceso'), table_name='contratos_procesados')
    op.drop_index(op.f('ix_contratos_procesados_fecha_publicacion_normalizada'), table_name='contratos_procesados')
    op.drop_index(op.f('ix_contratos_procesados_fecha_adjudicacion_normalizada'), table_name='contratos_procesados')
    op.drop_index(op.f('ix_contratos_procesados_entidad_normalizada'), table_name='contratos_procesados')
    op.create_index(op.f('ix_contratos_procesados_valor_contrato'), 'contratos_procesados', ['valor_contrato'], unique=False)
    op.create_index(op.f('ix_contratos_procesados_tipo_contrato'), 'contratos_procesados', ['tipo_contrato'], unique=False)
    op.create_index(op.f('ix_contratos_procesados_raw_data_id'), 'contratos_procesados', ['raw_data_id'], unique=False)
    op.create_index(op.f('ix_contratos_procesados_proveedor'), 'contratos_procesados', ['proveedor'], unique=False)
    op.create_index(op.f('ix_contratos_procesados_id_proceso'), 'contratos_procesados', ['id_proceso'], unique=False)
    op.create_index(op.f('ix_contratos_procesados_fecha_contrato'), 'contratos_procesados', ['fecha_contrato'], unique=False)
    op.create_index(op.f('ix_contratos_procesados_entidad'), 'contratos_procesados', ['entidad'], unique=False)
    op.alter_column('contratos_procesados', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('contratos_procesados', 'normalized_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_column('contratos_procesados', 'urlproceso')
    op.drop_column('contratos_procesados', 'departamento_entidad')
    op.drop_column('contratos_procesados', 'ciudad_entidad')
    op.drop_column('contratos_procesados', 'estado_normalizado')
    op.drop_column('contratos_procesados', 'modalidad_contratacion')
    op.drop_column('contratos_procesados', 'tipo_contrato_normalizado')
    op.drop_column('contratos_procesados', 'precio_base_normalizado')
    op.drop_column('contratos_procesados', 'valor_total_normalizado')
    op.drop_column('contratos_procesados', 'fecha_adjudicacion_normalizada')
    op.drop_column('contratos_procesados', 'fecha_publicacion_normalizada')
    op.drop_column('contratos_procesados', 'nit_proveedor')
    op.drop_column('contratos_procesados', 'proveedor_normalizado')
    op.drop_column('contratos_procesados', 'nit_entidad')
    op.drop_column('contratos_procesados', 'entidad_normalizada')
    op.drop_column('contratos_procesados', 'id_del_proceso')
    op.drop_column('contratos_procesados', 'raw_secop_id')
    op.drop_index(op.f('ix_contrato_anomalo_incompleto_raw_secop_id'), table_name='contrato_anomalo_incompleto')
    op.drop_index('ix_cai_motivo', table_name='contrato_anomalo_incompleto')
    op.drop_index('ix_cai_campo', table_name='contrato_anomalo_incompleto')
    op.drop_table('contrato_anomalo_incompleto')
    op.drop_index(op.f('ix_estadistica_campos_faltantes_nombre_campo'), table_name='estadistica_campos_faltantes')
    op.drop_table('estadistica_campos_faltantes')
    # ### end Alembic commands ###
