"""crear tabla raw_secop

Revision ID: 712163d002ed
Revises: ca580b3ba398
Create Date: 2026-05-10 21:32:52.296825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '712163d002ed'
down_revision: Union[str, Sequence[str], None] = 'ca580b3ba398'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fuentes_datos', 'formato',
               existing_type=postgresql.ENUM('JSON', 'CSV', 'XML', name='tipoformato'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fuentes_datos', 'formato',
               existing_type=postgresql.ENUM('JSON', 'CSV', 'XML', name='tipoformato'),
               nullable=True)
    # ### end Alembic commands ###
