"""FIX

Revision ID: 8a4ca16f08e8
Revises: ddf85c7d7b99
Create Date: 2026-05-13 18:44:15.794641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a4ca16f08e8'
down_revision: Union[str, Sequence[str], None] = 'ddf85c7d7b99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contrato_duplicado_periodo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('contrato_id', sa.BigInteger(), nullable=False),
    sa.Column('contrato_relacionado_id', sa.BigInteger(), nullable=False),
    sa.Column('proveedor', sa.String(length=255), nullable=False),
    sa.Column('entidad', sa.String(length=255), nullable=False),
    sa.Column('tipo_contrato', sa.String(length=255), nullable=True),
    sa.Column('modalidad_contratacion', sa.String(length=255), nullable=True),
    sa.Column('fecha_contrato', sa.Date(), nullable=False),
    sa.Column('fecha_relacionada', sa.Date(), nullable=False),
    sa.Column('diferencia_dias', sa.Integer(), nullable=False),
    sa.Column('duplicado_score', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('clasificacion_riesgo', sa.String(length=50), nullable=False),
    sa.Column('fecha_calculo', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contrato_duplicado_contrato_id', 'contrato_duplicado_periodo', ['contrato_id'], unique=False)
    op.create_index('ix_contrato_duplicado_riesgo', 'contrato_duplicado_periodo', ['clasificacion_riesgo'], unique=False)
    op.create_index('ix_contrato_duplicado_run_id', 'contrato_duplicado_periodo', ['run_id'], unique=False)
    op.create_index('ix_contrato_duplicado_score', 'contrato_duplicado_periodo', ['duplicado_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contrato_duplicado_score', table_name='contrato_duplicado_periodo')
    op.drop_index('ix_contrato_duplicado_run_id', table_name='contrato_duplicado_periodo')
    op.drop_index('ix_contrato_duplicado_riesgo', table_name='contrato_duplicado_periodo')
    op.drop_index('ix_contrato_duplicado_contrato_id', table_name='contrato_duplicado_periodo')
    op.drop_table('contrato_duplicado_periodo')
    # ### end Alembic commands ###
