"""initial

Revision ID: ddf85c7d7b99
Revises: 
Create Date: 2026-05-13 18:29:34.459580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ddf85c7d7b99'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contrato_outlier',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contrato_id', sa.BigInteger(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('grupo', sa.String(length=255), nullable=False),
    sa.Column('campo_analizado', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('q1', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('q3', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('iqr', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('limite_inferior', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('limite_superior', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('es_outlier', sa.Boolean(), nullable=False),
    sa.Column('direccion_outlier', sa.String(length=10), nullable=True),
    sa.Column('score', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('fecha_calculo', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contrato_outlier_contrato_id', 'contrato_outlier', ['contrato_id'], unique=False)
    op.create_index('ix_contrato_outlier_es_outlier', 'contrato_outlier', ['es_outlier'], unique=False)
    op.create_index('ix_contrato_outlier_grupo', 'contrato_outlier', ['grupo'], unique=False)
    op.create_index('ix_contrato_outlier_run_id', 'contrato_outlier', ['run_id'], unique=False)
    op.create_table('estadistica_campos_faltantes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nombre_campo', sa.String(length=100), nullable=False),
    sa.Column('contador_faltantes', sa.Integer(), nullable=False),
    sa.Column('porcentaje_total', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estadistica_campos_faltantes_nombre_campo'), 'estadistica_campos_faltantes', ['nombre_campo'], unique=True)
    op.create_table('fuentes_datos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('formato', sa.Enum('JSON', 'CSV', 'XML', name='tipoformato'), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('frecuencia_dias', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('ultima_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_fuentes_datos_id'), 'fuentes_datos', ['id'], unique=False)
    op.create_table('raw_secop',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('fuente_id', sa.Integer(), nullable=False),
    sa.Column('entidad', sa.Text(), nullable=True),
    sa.Column('nit_entidad', sa.String(length=50), nullable=True),
    sa.Column('departamento_entidad', sa.String(length=100), nullable=True),
    sa.Column('ciudad_entidad', sa.String(length=100), nullable=True),
    sa.Column('ordenentidad', sa.Text(), nullable=True),
    sa.Column('codigo_pci', sa.String(length=50), nullable=True),
    sa.Column('codigo_entidad', sa.Numeric(), nullable=True),
    sa.Column('id_del_proceso', sa.String(length=100), nullable=True),
    sa.Column('referencia_del_proceso', sa.Text(), nullable=True),
    sa.Column('ppi', sa.Text(), nullable=True),
    sa.Column('id_del_portafolio', sa.String(length=100), nullable=True),
    sa.Column('nombre_del_procedimiento', sa.Text(), nullable=True),
    sa.Column('descripci_n_del_procedimiento', sa.Text(), nullable=True),
    sa.Column('fase', sa.String(length=100), nullable=True),
    sa.Column('estado_del_procedimiento', sa.String(length=100), nullable=True),
    sa.Column('id_estado_del_procedimiento', sa.Numeric(), nullable=True),
    sa.Column('estado_de_apertura_del_proceso', sa.String(length=100), nullable=True),
    sa.Column('estado_resumen', sa.String(length=100), nullable=True),
    sa.Column('fecha_de_publicacion_del', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_de_ultima_publicaci', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_de_publicacion_fase', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_de_publicacion_fase_1', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_de_publicacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_de_publicacion_fase_2', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_de_publicacion_fase_3', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_de_recepcion_de', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_de_apertura_de_respuesta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_de_apertura_efectiva', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_adjudicacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('precio_base', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('modalidad_de_contratacion', sa.String(length=200), nullable=True),
    sa.Column('justificaci_n_modalidad_de', sa.Text(), nullable=True),
    sa.Column('duracion', sa.Numeric(), nullable=True),
    sa.Column('unidad_de_duracion', sa.String(length=50), nullable=True),
    sa.Column('tipo_de_contrato', sa.String(length=200), nullable=True),
    sa.Column('subtipo_de_contrato', sa.String(length=200), nullable=True),
    sa.Column('categorias_adicionales', sa.Text(), nullable=True),
    sa.Column('codigo_principal_de_categoria', sa.String(length=100), nullable=True),
    sa.Column('ciudad_de_la_unidad_de', sa.String(length=100), nullable=True),
    sa.Column('nombre_de_la_unidad_de', sa.Text(), nullable=True),
    sa.Column('proveedores_invitados', sa.Numeric(), nullable=True),
    sa.Column('proveedores_con_invitacion', sa.Numeric(), nullable=True),
    sa.Column('visualizaciones_del', sa.Numeric(), nullable=True),
    sa.Column('proveedores_que_manifestaron', sa.Numeric(), nullable=True),
    sa.Column('respuestas_al_procedimiento', sa.Numeric(), nullable=True),
    sa.Column('respuestas_externas', sa.Numeric(), nullable=True),
    sa.Column('conteo_de_respuestas_a_ofertas', sa.Numeric(), nullable=True),
    sa.Column('proveedores_unicos_con', sa.Numeric(), nullable=True),
    sa.Column('numero_de_lotes', sa.Numeric(), nullable=True),
    sa.Column('adjudicado', sa.String(length=10), nullable=True),
    sa.Column('id_adjudicacion', sa.String(length=100), nullable=True),
    sa.Column('codigoproveedor', sa.String(length=100), nullable=True),
    sa.Column('departamento_proveedor', sa.String(length=100), nullable=True),
    sa.Column('ciudad_proveedor', sa.String(length=100), nullable=True),
    sa.Column('valor_total_adjudicacion', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('nombre_del_adjudicador', sa.Text(), nullable=True),
    sa.Column('nombre_del_proveedor', sa.Text(), nullable=True),
    sa.Column('nit_del_proveedor_adjudicado', sa.String(length=50), nullable=True),
    sa.Column('urlproceso', sa.Text(), nullable=True),
    sa.Column('sincronizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['fuente_id'], ['fuentes_datos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_raw_secop_adjudicado', 'raw_secop', ['adjudicado', 'valor_total_adjudicacion'], unique=False)
    op.create_index('ix_raw_secop_entidad', 'raw_secop', ['entidad'], unique=False)
    op.create_index('ix_raw_secop_entidad_fecha', 'raw_secop', ['nit_entidad', 'fecha_de_publicacion_del'], unique=False)
    op.create_index('ix_raw_secop_estado', 'raw_secop', ['estado_del_procedimiento'], unique=False)
    op.create_index('ix_raw_secop_fecha_pub', 'raw_secop', ['fecha_de_publicacion_del'], unique=False)
    op.create_index('ix_raw_secop_fuente', 'raw_secop', ['fuente_id'], unique=False)
    op.create_index('ix_raw_secop_id_proceso', 'raw_secop', ['id_del_proceso'], unique=True)
    op.create_index('ix_raw_secop_modalidad', 'raw_secop', ['modalidad_de_contratacion'], unique=False)
    op.create_index('ix_raw_secop_nit_entidad', 'raw_secop', ['nit_entidad'], unique=False)
    op.create_table('sincronizacion_historial',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fuente_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registros_traidos', sa.BigInteger(), nullable=True),
    sa.Column('registros_insertados', sa.BigInteger(), nullable=True),
    sa.Column('registros_duplicados', sa.BigInteger(), nullable=True),
    sa.Column('estado', sa.Enum('EN_PROCESO', 'EXITOSO', 'ERROR', name='estadosync'), nullable=True),
    sa.Column('mensaje_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['fuente_id'], ['fuentes_datos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contratos_procesados',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('raw_secop_id', sa.BigInteger(), nullable=False),
    sa.Column('id_del_proceso', sa.String(length=100), nullable=True),
    sa.Column('entidad_normalizada', sa.Text(), nullable=True),
    sa.Column('nit_entidad', sa.String(length=50), nullable=True),
    sa.Column('proveedor_normalizado', sa.Text(), nullable=True),
    sa.Column('nit_proveedor', sa.String(length=50), nullable=True),
    sa.Column('fecha_publicacion_normalizada', sa.Date(), nullable=True),
    sa.Column('fecha_adjudicacion_normalizada', sa.Date(), nullable=True),
    sa.Column('valor_total_normalizado', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('precio_base_normalizado', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('tipo_contrato_normalizado', sa.String(length=200), nullable=True),
    sa.Column('modalidad_contratacion', sa.String(length=200), nullable=True),
    sa.Column('estado_normalizado', sa.String(length=100), nullable=True),
    sa.Column('ciudad_entidad', sa.String(length=100), nullable=True),
    sa.Column('departamento_entidad', sa.String(length=100), nullable=True),
    sa.Column('urlproceso', sa.Text(), nullable=True),
    sa.Column('normalized_hash', sa.String(length=64), nullable=False),
    sa.Column('es_incompleto', sa.Boolean(), nullable=True),
    sa.Column('cantidad_campos_faltantes', sa.Integer(), nullable=True),
    sa.Column('campos_faltantes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('nivel_confianza', sa.Integer(), nullable=True),
    sa.Column('es_sospechoso', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_secop_id'], ['raw_secop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contratos_procesados_entidad_normalizada'), 'contratos_procesados', ['entidad_normalizada'], unique=False)
    op.create_index(op.f('ix_contratos_procesados_es_incompleto'), 'contratos_procesados', ['es_incompleto'], unique=False)
    op.create_index(op.f('ix_contratos_procesados_es_sospechoso'), 'contratos_procesados', ['es_sospechoso'], unique=False)
    op.create_index(op.f('ix_contratos_procesados_fecha_adjudicacion_normalizada'), 'contratos_procesados', ['fecha_adjudicacion_normalizada'], unique=False)
    op.create_index(op.f('ix_contratos_procesados_fecha_publicacion_normalizada'), 'contratos_procesados', ['fecha_publicacion_normalizada'], unique=False)
    op.create_index(op.f('ix_contratos_procesados_id_del_proceso'), 'contratos_procesados', ['id_del_proceso'], unique=False)
    op.create_index(op.f('ix_contratos_procesados_nivel_confianza'), 'contratos_procesados', ['nivel_confianza'], unique=False)
    op.create_index(op.f('ix_contratos_procesados_normalized_hash'), 'contratos_procesados', ['normalized_hash'], unique=True)
    op.create_index(op.f('ix_contratos_procesados_proveedor_normalizado'), 'contratos_procesados', ['proveedor_normalizado'], unique=False)
    op.create_index(op.f('ix_contratos_procesados_raw_secop_id'), 'contratos_procesados', ['raw_secop_id'], unique=False)
    op.create_index(op.f('ix_contratos_procesados_tipo_contrato_normalizado'), 'contratos_procesados', ['tipo_contrato_normalizado'], unique=False)
    op.create_index(op.f('ix_contratos_procesados_valor_total_normalizado'), 'contratos_procesados', ['valor_total_normalizado'], unique=False)
    op.create_index('ix_cp_entidad_fecha', 'contratos_procesados', ['entidad_normalizada', 'fecha_publicacion_normalizada'], unique=False)
    op.create_index('ix_cp_tipo_valor', 'contratos_procesados', ['tipo_contrato_normalizado', 'valor_total_normalizado'], unique=False)
    op.create_table('contrato_anomalo_incompleto',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('raw_secop_id', sa.BigInteger(), nullable=False),
    sa.Column('id_contrato_procesado', sa.BigInteger(), nullable=True),
    sa.Column('motivo', sa.String(length=50), nullable=True),
    sa.Column('valor_detectado', sa.Text(), nullable=True),
    sa.Column('tipo_anomalia', sa.String(length=50), nullable=True),
    sa.Column('valor_original', sa.Text(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('campo_afectado', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_contrato_procesado'], ['contratos_procesados.id'], ),
    sa.ForeignKeyConstraint(['raw_secop_id'], ['raw_secop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cai_campo', 'contrato_anomalo_incompleto', ['campo_afectado'], unique=False)
    op.create_index('ix_cai_motivo', 'contrato_anomalo_incompleto', ['motivo'], unique=False)
    op.create_index('ix_cai_tipo_anomalia', 'contrato_anomalo_incompleto', ['tipo_anomalia'], unique=False)
    op.create_index(op.f('ix_contrato_anomalo_incompleto_id_contrato_procesado'), 'contrato_anomalo_incompleto', ['id_contrato_procesado'], unique=False)
    op.create_index(op.f('ix_contrato_anomalo_incompleto_raw_secop_id'), 'contrato_anomalo_incompleto', ['raw_secop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contrato_anomalo_incompleto_raw_secop_id'), table_name='contrato_anomalo_incompleto')
    op.drop_index(op.f('ix_contrato_anomalo_incompleto_id_contrato_procesado'), table_name='contrato_anomalo_incompleto')
    op.drop_index('ix_cai_tipo_anomalia', table_name='contrato_anomalo_incompleto')
    op.drop_index('ix_cai_motivo', table_name='contrato_anomalo_incompleto')
    op.drop_index('ix_cai_campo', table_name='contrato_anomalo_incompleto')
    op.drop_table('contrato_anomalo_incompleto')
    op.drop_index('ix_cp_tipo_valor', table_name='contratos_procesados')
    op.drop_index('ix_cp_entidad_fecha', table_name='contratos_procesados')
    op.drop_index(op.f('ix_contratos_procesados_valor_total_normalizado'), table_name='contratos_procesados')
    op.drop_index(op.f('ix_contratos_procesados_tipo_contrato_normalizado'), table_name='contratos_procesados')
    op.drop_index(op.f('ix_contratos_procesados_raw_secop_id'), table_name='contratos_procesados')
    op.drop_index(op.f('ix_contratos_procesados_proveedor_normalizado'), table_name='contratos_procesados')
    op.drop_index(op.f('ix_contratos_procesados_normalized_hash'), table_name='contratos_procesados')
    op.drop_index(op.f('ix_contratos_procesados_nivel_confianza'), table_name='contratos_procesados')
    op.drop_index(op.f('ix_contratos_procesados_id_del_proceso'), table_name='contratos_procesados')
    op.drop_index(op.f('ix_contratos_procesados_fecha_publicacion_normalizada'), table_name='contratos_procesados')
    op.drop_index(op.f('ix_contratos_procesados_fecha_adjudicacion_normalizada'), table_name='contratos_procesados')
    op.drop_index(op.f('ix_contratos_procesados_es_sospechoso'), table_name='contratos_procesados')
    op.drop_index(op.f('ix_contratos_procesados_es_incompleto'), table_name='contratos_procesados')
    op.drop_index(op.f('ix_contratos_procesados_entidad_normalizada'), table_name='contratos_procesados')
    op.drop_table('contratos_procesados')
    op.drop_table('sincronizacion_historial')
    op.drop_index('ix_raw_secop_nit_entidad', table_name='raw_secop')
    op.drop_index('ix_raw_secop_modalidad', table_name='raw_secop')
    op.drop_index('ix_raw_secop_id_proceso', table_name='raw_secop')
    op.drop_index('ix_raw_secop_fuente', table_name='raw_secop')
    op.drop_index('ix_raw_secop_fecha_pub', table_name='raw_secop')
    op.drop_index('ix_raw_secop_estado', table_name='raw_secop')
    op.drop_index('ix_raw_secop_entidad_fecha', table_name='raw_secop')
    op.drop_index('ix_raw_secop_entidad', table_name='raw_secop')
    op.drop_index('ix_raw_secop_adjudicado', table_name='raw_secop')
    op.drop_table('raw_secop')
    op.drop_index(op.f('ix_fuentes_datos_id'), table_name='fuentes_datos')
    op.drop_table('fuentes_datos')
    op.drop_index(op.f('ix_estadistica_campos_faltantes_nombre_campo'), table_name='estadistica_campos_faltantes')
    op.drop_table('estadistica_campos_faltantes')
    op.drop_index('ix_contrato_outlier_run_id', table_name='contrato_outlier')
    op.drop_index('ix_contrato_outlier_grupo', table_name='contrato_outlier')
    op.drop_index('ix_contrato_outlier_es_outlier', table_name='contrato_outlier')
    op.drop_index('ix_contrato_outlier_contrato_id', table_name='contrato_outlier')
    op.drop_table('contrato_outlier')
    # ### end Alembic commands ###
