"""Add contrato_duplicado_periodo

Revision ID: ed41f5b67613
Revises: efaebb9a5030
Create Date: 2026-05-13 18:01:38.508966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed41f5b67613'
down_revision: Union[str, Sequence[str], None] = 'efaebb9a5030'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
