"""identificacion_incompletos

Revision ID: f056fbb51fbc
Revises: 6486afd78c3a
Create Date: 2026-05-12 17:27:30.825770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f056fbb51fbc'
down_revision: Union[str, Sequence[str], None] = '6486afd78c3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contrato_anomalo_incompleto', sa.Column('id_contrato_procesado', sa.BigInteger(), nullable=True))
    op.add_column('contrato_anomalo_incompleto', sa.Column('tipo_anomalia', sa.String(length=50), nullable=True))
    op.add_column('contrato_anomalo_incompleto', sa.Column('valor_original', sa.Text(), nullable=True))
    op.add_column('contrato_anomalo_incompleto', sa.Column('descripcion', sa.Text(), nullable=True))
    op.alter_column('contrato_anomalo_incompleto', 'motivo',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_index(op.f('ix_contrato_anomalo_incompleto_id_contrato_procesado'), 'contrato_anomalo_incompleto', ['id_contrato_procesado'], unique=False)
    op.create_foreign_key(None, 'contrato_anomalo_incompleto', 'contratos_procesados', ['id_contrato_procesado'], ['id'])
    op.add_column('contratos_procesados', sa.Column('es_incompleto', sa.Boolean(), nullable=True))
    op.add_column('contratos_procesados', sa.Column('cantidad_campos_faltantes', sa.Integer(), nullable=True))
    op.add_column('contratos_procesados', sa.Column('campos_faltantes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('contratos_procesados', sa.Column('nivel_confianza', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_contratos_procesados_es_incompleto'), 'contratos_procesados', ['es_incompleto'], unique=False)
    op.create_index(op.f('ix_contratos_procesados_nivel_confianza'), 'contratos_procesados', ['nivel_confianza'], unique=False)
    op.add_column('estadistica_campos_faltantes', sa.Column('porcentaje_total', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estadistica_campos_faltantes', 'porcentaje_total')
    op.drop_index(op.f('ix_contratos_procesados_nivel_confianza'), table_name='contratos_procesados')
    op.drop_index(op.f('ix_contratos_procesados_es_incompleto'), table_name='contratos_procesados')
    op.drop_column('contratos_procesados', 'nivel_confianza')
    op.drop_column('contratos_procesados', 'campos_faltantes')
    op.drop_column('contratos_procesados', 'cantidad_campos_faltantes')
    op.drop_column('contratos_procesados', 'es_incompleto')
    op.drop_constraint(None, 'contrato_anomalo_incompleto', type_='foreignkey')
    op.drop_index(op.f('ix_contrato_anomalo_incompleto_id_contrato_procesado'), table_name='contrato_anomalo_incompleto')
    op.alter_column('contrato_anomalo_incompleto', 'motivo',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('contrato_anomalo_incompleto', 'descripcion')
    op.drop_column('contrato_anomalo_incompleto', 'valor_original')
    op.drop_column('contrato_anomalo_incompleto', 'tipo_anomalia')
    op.drop_column('contrato_anomalo_incompleto', 'id_contrato_procesado')
    # ### end Alembic commands ###
