"""deteccion_valores_sospechosos

Revision ID: f590f8667ce7
Revises: f056fbb51fbc
Create Date: 2026-05-12 17:38:30.580750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f590f8667ce7'
down_revision: Union[str, Sequence[str], None] = 'f056fbb51fbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_cai_tipo_anomalia', 'contrato_anomalo_incompleto', ['tipo_anomalia'], unique=False)
    op.add_column('contratos_procesados', sa.Column('es_sospechoso', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_contratos_procesados_es_sospechoso'), 'contratos_procesados', ['es_sospechoso'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contratos_procesados_es_sospechoso'), table_name='contratos_procesados')
    op.drop_column('contratos_procesados', 'es_sospechoso')
    op.drop_index('ix_cai_tipo_anomalia', table_name='contrato_anomalo_incompleto')
    # ### end Alembic commands ###
