"""Add riesgo and pesos

Revision ID: fe1c0b717809
Revises: eda09f4d1ba0
Create Date: 2026-05-13 21:14:06.015365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe1c0b717809'
down_revision: Union[str, Sequence[str], None] = 'eda09f4d1ba0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('peso_anomalia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo_anomalia', sa.String(length=50), nullable=False),
    sa.Column('peso', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peso_anomalia_tipo_anomalia'), 'peso_anomalia', ['tipo_anomalia'], unique=True)
    op.create_table('riesgo_proveedor',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('proveedor', sa.String(), nullable=False),
    sa.Column('nit_proveedor', sa.String(length=50), nullable=True),
    sa.Column('max_score_outlier', sa.Numeric(), nullable=False),
    sa.Column('max_score_duplicado', sa.Numeric(), nullable=False),
    sa.Column('score_directo', sa.Numeric(), nullable=False),
    sa.Column('score_final', sa.Numeric(), nullable=False),
    sa.Column('clasificacion_riesgo', sa.String(length=20), nullable=False),
    sa.Column('pesos_aplicados', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fecha_calculo', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_riesgo_proveedor_clasificacion_riesgo'), 'riesgo_proveedor', ['clasificacion_riesgo'], unique=False)
    op.create_index(op.f('ix_riesgo_proveedor_proveedor'), 'riesgo_proveedor', ['proveedor'], unique=False)
    op.create_index(op.f('ix_riesgo_proveedor_run_id'), 'riesgo_proveedor', ['run_id'], unique=False)
    op.create_index('ix_riesgo_proveedor_score', 'riesgo_proveedor', ['score_final', 'clasificacion_riesgo'], unique=False)
    op.create_index(op.f('ix_riesgo_proveedor_score_final'), 'riesgo_proveedor', ['score_final'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_riesgo_proveedor_score_final'), table_name='riesgo_proveedor')
    op.drop_index('ix_riesgo_proveedor_score', table_name='riesgo_proveedor')
    op.drop_index(op.f('ix_riesgo_proveedor_run_id'), table_name='riesgo_proveedor')
    op.drop_index(op.f('ix_riesgo_proveedor_proveedor'), table_name='riesgo_proveedor')
    op.drop_index(op.f('ix_riesgo_proveedor_clasificacion_riesgo'), table_name='riesgo_proveedor')
    op.drop_table('riesgo_proveedor')
    op.drop_index(op.f('ix_peso_anomalia_tipo_anomalia'), table_name='peso_anomalia')
    op.drop_table('peso_anomalia')
    # ### end Alembic commands ###
